# Generated by Django 6.0.6 on 2026-08-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_choices',
            new_name='transaction_type',
        ),
    ]
